instrumentation:
  root: src
  extensions:
    - .js
  default-excludes: true
  excludes:
    - "**/*.spec.js"
  variable: __coverage__
  es-modules: true
  include-all-sources: true
reporting:
  print: summary
  reports:
    - lcov
  dir: ./test/coverage

